In [17]:
import numpy as np
import cv2

In [18]:
img = cv2.imread('./data/friends.jpg')
img_copy =img.copy()


cv2.imshow('Imagen',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# Load cascade classifier
haar = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')

In [20]:
# step-1: convert iamge to grayscale
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [21]:
# step-2: apply grayscale image to cascade classifier
face_rect = haar.detectMultiScale(gray,1.3,5)
print(face_rect)

[[256  88  98  98]
 [127 107  97  97]
 [405  90  99  99]]


In [22]:
# step-3: draw bounding box
from email.mime import image


for x,y,w,h in face_rect:
    cv2.rectangle(img, (x,y),(x+w,y+h),(0,255,0),2)

cv2.imshow('detected faces',img)
cv2.waitKey(0)
cv2.destroyAllWindows()